name: 'blog feed ci'
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 6 * * *'

jobs:
  readme:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.feed.outputs.changed }}
      items: ${{ steps.feed.outputs.items }}
    steps:
      - uses: sarisia/setup-icu@v1
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull origin main
      - name: tech blog
        uses: sarisia/actions-readme-feed@v1.6.2
        id: tech
        with:
          url: 'https://blog.towavephone.com/rss.xml'
          file: 'README.md'
          format: "${year}${02month}${02day}：[${title}](${url})  "
          start_flag: "<!-- tech blog start -->"
          end_flag: "<!-- tech blog end -->"
          locale: 'zh-CN'
          max_entry: 6
      - name: life blog
        uses: sarisia/actions-readme-feed@v1.6.2
        id: life
        with:
          url: 'https://www.towavephone.com/atom.xml'
          file: 'README.md'
          format: "${year}${02month}${02day}：[${title}](${url})  "
          start_flag: "<!-- life blog start -->"
          end_flag: "<!-- life blog end -->"
          locale: 'zh-CN'
          max_entry: 6
      - name: push to master
        if: ${{ steps.tech.outputs.changed == true || steps.life.outputs.changed == true }}
        id: commit
        uses: sarisia/actions-commit@master
        with:
          message: "docs: update feed"
